# Generated by Django 5.1.2 on 2024-10-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(default='Cliente Anónimo', max_length=50)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('llevar', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=50)),
                ('observaciones', models.CharField(choices=[('sin salsas', 'Sin Salsas'), ('sin salsa blanca', 'Sin Salsa Blanca'), ('con mostaza', 'Con Mostaza'), ('sin salsa roja', 'Sin Salsa Roja'), ('sin mostaza', 'Sin Mostaza'), ('sin cebolla', 'Sin Cebolla'), ('sin pepinillos', 'Sin Pepinillos'), ('con todas las salsas', 'Con Todas las Salsas')], default='con todas las salsas', max_length=50)),
                ('estado', models.CharField(choices=[('en espera', 'En Espera'), ('en preparacion', 'En Preparación'), ('terminado', 'Terminado')], default='en espera', max_length=50)),
            ],
        ),
    ]
